import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { GetServerSideProps } from 'next';

import { news, Card } from '../components/Card';

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch(`https://api.github.com/repos/ojeelafriend/rickandmortyjs/releases`, {
    headers: {
      Authorization: `Bearer ${process.env.NEXT_PUBLIC_GIT_TOKEN}`,
    },
  });

  const result = await response.json();

  let news: news[] = [];

  for (const item of result) {
    news = [
      ...news,
      {
        title: item.name,
        body: item.body,
        author: item.author.login,
        // image: item.assets[0]?.url,
        creation: item.published_at,
      },
    ];
  }

  return {
    props: {
      arrayNews: news,
    },
  };
};

export default function Home({ arrayNews }: { arrayNews: news[] }) {
  return (
    <>
      <Head>
        <title>Changelog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Changelog</h1>
        {arrayNews.map(({ title, body, image, author, creation }) => {
          return <Card title={title} body={body} author={author} creation={creation} />;
        })}
      </main>
    </>
  );
}
